name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Writing cypress.env.json file
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          # build: npm run build
          # start: npm start
          start: npm run cypress:open:cli
  artillery:
    runs-on: ubuntu-latest
    container: artilleryio/artillery:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Execute load tests
        env:
          BASE_URL_TARGET: "${{ secrets.BASE_URL_TARGET }}"
        run: /home/node/artillery/bin/run run performanceTests/performance.yml